baseURL: http://localhost
projectName: JobLinker
scenarios:
  - path: ./benchmark/scenario1.js
    name: Charge la page de recherche et consultation des offres
containers:
  - joblinker-static_hosting-1
  - joblinker-backend-1
